# -*- coding: utf-8 -*-
"""RetailCleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12jHUOHWYlHKZ9B1Kw1pdB1x0-2ud3ajQ
"""

import pandas as pd

#Imports Retail data to be cleaned
Retail = pd.read_csv('/Retail.csv')

#Checks for correct data
Retail.head()

#This code groups the data by the primary keys, then merges duplicate data so that
#transactions for the same product code within the same invoice are together
new_Retail = Retail.groupby(['InvoiceNo','InvoiceDate','StockCode']).sum()
#Resets index so group_by becomes dataframe
new_Retail = new_Retail.reset_index()

#Checks an example whether data was cleaned
new_Retail[(new_Retail['InvoiceNo'] == 580137) & (new_Retail["InvoiceDate"] == '2017-12-31') & (new_Retail['StockCode'] == 21034)]

new_Retail

#Writes cleaned data to new csv
new_Retail.to_csv('Clean_Retail.csv', index = False)

clean_Retail = pd.read_csv('/Clean_Retail.csv')

#Check clean data
clean_Retail

